"""Desktop bundle with Ollama, llama.cpp and (Apple Silicon) MLX. Build on each target OS
in a clean environment."""

import platform
import sys
import tomllib
from pathlib import Path

from PyInstaller.utils.hooks import collect_all, collect_data_files, collect_submodules

root = Path(SPECPATH).parent
version = tomllib.loads((root / "pyproject.toml").read_text())["project"]["version"]
pdfium_data, pdfium_binaries, pdfium_imports = collect_all("pypdfium2_raw")
# Model runtimes: native libraries (ggml, Metal shaders) and model architectures that
# mlx_lm imports by name at load time. MLX only exists for Apple Silicon macOS.
runtime_data, runtime_binaries, runtime_imports = [], [], []
packages = ["llama_cpp"]
if sys.platform == "darwin" and platform.machine() == "arm64":
    packages += ["mlx", "mlx_lm"]
for package in packages:
    try:
        datas_, binaries_, imports_ = collect_all(package)
    except Exception:
        datas_, binaries_, imports_ = [], [], []
    if package == "llama_cpp" and not binaries_:
        raise SystemExit("llama-cpp-python is missing: sync the packaging env with --extra gguf")
    if package == "mlx" and not binaries_:
        raise SystemExit("MLX is missing: sync the packaging env with --extra mlx")
    if package == "mlx_lm" and not imports_:
        raise SystemExit("mlx-lm is missing: sync the packaging env with --extra mlx")
    runtime_data += datas_
    runtime_binaries += binaries_
    runtime_imports += imports_

a = Analysis(
    [str(root / "packaging" / "desktop.py")],
    pathex=[str(root / "src")],
    binaries=pdfium_binaries + runtime_binaries,
    datas=[
        (str(root / "src/llm_engine/store/schema.sql"), "llm_engine/store"),
        # The migration loader executes these files by path, outside the module archive.
        (str(root / "src/llm_engine/store/migrations/*.py"), "llm_engine/store/migrations"),
        (str(root / "src/llm_manager_app/assets/*.svg"), "llm_manager_app/assets"),
        (str(root / "src/llm_manager_app/assets/*.png"), "llm_manager_app/assets"),
        # GPL-3.0: distributed copies carry the license text, and bundled
        # libraries' notices (generated by scripts/third_party_notices.py).
        (str(root / "LICENSE"), "."),
        (str(root / "build" / "THIRD_PARTY_NOTICES.txt"), "."),
    ] + collect_data_files("markdown") + collect_data_files("pptx")
      # python-pptx resolves notes templates through oxml/../templates. The oxml
      # directory must exist on disk even though its modules are in the archive.
      + collect_data_files("pptx", include_py_files=True, includes=["oxml/__init__.py"])
      + collect_data_files("reportlab") + pdfium_data + runtime_data,
    hiddenimports=collect_submodules("uvicorn") + collect_submodules("markdown.extensions")
                  + pdfium_imports + runtime_imports,
    # mlx_lm only needs transformers' tokenizers; never pull in a torch installation.
    excludes=["torch", "tensorflow", "flax", "jax", "PyQt5", "PyQt6"],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Orchevian",
    debug=False,
    strip=False,
    upx=False,
    console=False,
    icon=str(root / "packaging" / "icons" / "orchevian.ico"),
)
collection = COLLECT(
    exe, a.binaries, a.datas, strip=False, upx=False, name="Orchevian",
)
if sys.platform == "darwin":
    app = BUNDLE(
        collection,
        name="Orchevian.app",
        bundle_identifier="com.orchevian.desktop",
        icon=str(root / "packaging" / "icons" / "orchevian.icns"),
        version=version,
        info_plist={
            "CFBundleName": "Orchevian",
            "CFBundleDisplayName": "Orchevian",
            "CFBundleShortVersionString": version,
            "CFBundleVersion": version,
            "NSHumanReadableCopyright": "Copyright © 2026 Seth Hardin. GPL-3.0-or-later.",
            "LSApplicationCategoryType": "public.app-category.productivity",
            "LSMinimumSystemVersion": "12.0",
            "NSHighResolutionCapable": True,
            # Follow the system's light or dark appearance.
            "NSRequiresAquaSystemAppearance": False,
        },
    )
